### ISSUE TITLE
Coding policy suggestions

### ISSUE THREAD

**Issue by revington** [findhit/proxywrap#17]
I'll think that the following would enrich this project.
- Integration with travis testing LTS and stable versions of node
- a code convention definition 
- a .eslintrc, .jshintrc or something similar 
- Better code readability I.E by replacing magic numbers with constants. `parseInt(header[4], 10);` → `parseInt(header[REMOTE_PORT_HEADER], 10);`
- Refactoring functionality instead of inlining in order to enforce readablity

I can help with that if you agreed

**Comment by cusspvz** [comment]
> Integration with travis testing LTS and stable versions of node

It was using our old internal CI, but we moved it and some of our OS projects weren't updated, used Travis instead.

> a code convention definition
> I can help with that if you agreed

If you may help us here it would be great!

We like to:
* use `var` declarations on every vars instead of aggregating them (we didn't have this before, we added it since its easier to manage them.
* avoid `;`, since javascript has `asi`
* spaces instead of tabs (we use 4)
* spaces, spaces and more spaces: code should be readable, by any one.
```

// Instead of:
if('some'=='condition'){
    return 'yolo'
}

// We prefer:
if ( 'some' == 'condition' ) {
    return 'yolo'
}

```

* brackets, always write them on ifs, even that you just want to return. (this allows anyone to fastly change code without having to break lines, identate, and so on.
```
// Instead of:
if ( condition ) return

// We prefer:
if ( condition ) {
    return
}
```

> Better code readability I.E by replacing magic numbers with constants.

Agreed. Do you have some suggestion regarding a new folder structure having in mind a file for constants?

**Comment by revington** [comment]
I'm going to open different PR for each item so we can discuss each thing in a separate thread
